load_paths:
  - lib/assets/javascripts
  - lib/assets/stylesheets
  - vendor/assets/javascripts
  - vendor/assets/stylesheets
  - test/javascripts/
  - turbolinks-source: lib/assets/javascripts
  - jquery-rails: vendor/assets/javascripts
  - lodash-rails: vendor/assets/javascripts
  - tao_on_rails:
    - lib/assets/javascripts
    - lib/assets/stylesheets
    - vendor/assets/javascripts
    - vendor/assets/stylesheets

logical_paths:
  - tao.js
  - tao.css
  - tao/ui.css
  - tao/ui.js
  - tao_ui_test.js

plugins:
  sauce_labs:
    tunnel_timeout: 120
    browsers:
      Google Chrome:
        os: Mac, Windows
        version: -2
      Firefox:
        os: Mac, Windows
        version: -2
      Safari:
        platform: Mac
        version: -2
      Microsoft Edge:
        version: -2
      iPhone:
        version: [10.0, 9.3, 8.4]
      Android:
        version: [6.0, 5.1, 4.4]
